# Generated by Django 4.1.9 on 2023-05-18 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sede', '0002_sede_produtosede_precio'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Precio',
        ),
    ]
