# Generated by Django 4.1.9 on 2023-05-18 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Venta', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='venta',
            old_name='mesa',
            new_name='mesa_id',
        ),
        migrations.RenameField(
            model_name='venta',
            old_name='sede',
            new_name='sede_id',
        ),
        migrations.RenameField(
            model_name='ventaproducto',
            old_name='producto',
            new_name='producto_id',
        ),
        migrations.RenameField(
            model_name='ventaproducto',
            old_name='venta',
            new_name='venta_id',
        ),
    ]
