# Generated by Django 4.1.9 on 2023-05-18 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Provedor', '0002_precio'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Precio',
        ),
    ]
