# Generated by Django 4.1.9 on 2023-05-18 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Provedor', '0006_proveedorproducto'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProveedorProducto',
        ),
    ]
