# Generated by Django 4.1.9 on 2023-05-18 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Sede', '0003_delete_precio'),
        ('Provedor', '0007_delete_proveedorproducto'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProveedorProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_compra', models.DecimalField(decimal_places=0, max_digits=10)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sede.producto')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Provedor.proveedor')),
            ],
        ),
    ]
