# Generated by Django 4.1.9 on 2023-05-18 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Provedor', '0008_proveedorproducto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proveedorproducto',
            old_name='producto',
            new_name='producto_id',
        ),
        migrations.RenameField(
            model_name='proveedorproducto',
            old_name='proveedor',
            new_name='proveedor_id',
        ),
    ]
