# Generated by Django 4.1.9 on 2023-05-18 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Sede', '0002_sede_produtosede_precio'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoEmpleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=30)),
                ('apellidos', models.CharField(max_length=30)),
                ('correo', models.CharField(max_length=30)),
                ('direccion', models.CharField(max_length=30)),
                ('telefono', models.IntegerField()),
                ('estado', models.IntegerField()),
                ('sede', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sede.sede')),
                ('tipo_empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Usuario.tipoempleado')),
            ],
        ),
    ]
