# Generated by Django 4.1.9 on 2023-05-19 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Usuario', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empleado',
            old_name='sede',
            new_name='sede_id',
        ),
        migrations.RenameField(
            model_name='empleado',
            old_name='tipo_empleado',
            new_name='tipo_empleado_id',
        ),
    ]
