# Generated by Django 4.1.9 on 2023-05-19 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuario', '0002_rename_sede_empleado_sede_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='contraseña',
            field=models.CharField(default=2, max_length=30),
            preserve_default=False,
        ),
    ]
