# Generated by Django 4.1.9 on 2023-05-19 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Usuario', '0003_empleado_contraseña'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empleado',
            old_name='apellidos',
            new_name='lastname',
        ),
        migrations.RenameField(
            model_name='empleado',
            old_name='contraseña',
            new_name='mail',
        ),
        migrations.RenameField(
            model_name='empleado',
            old_name='correo',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='empleado',
            old_name='nombres',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='empleado',
            old_name='telefono',
            new_name='phone',
        ),
        migrations.RenameField(
            model_name='empleado',
            old_name='tipo_empleado_id',
            new_name='rolId',
        ),
        migrations.RenameField(
            model_name='empleado',
            old_name='sede_id',
            new_name='sedeId',
        ),
    ]
